import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to 
        </h1>

        <p className={styles.description}>
          Get started 
        </p>

        <div className={styles.grid}>
          <a href="https://www.google.com/search?q=pizza&oq=pizza&aqs=chrome..69i57j0i512j46i10i131i199i433i465j46i131i199i433i465j0i512l2j46i199i465i512j0i512j0i433i512j0i131i433i512.1533j0j7&sourceid=chrome&ie=UTF-8" className={styles.card}>
            <h2>Pizza &rarr;</h2>
            <p>Find Pizza on search engine.</p>
          </a>

          <a href="https://www.google.com/search?q=Husky&sxsrf=ALiCzsbWjnaJHri3C1RefQaJ7oyM0IkBFQ%3A1664127057397&ei=UZAwY5HyF9Dk-Qbw36XwDg&ved=0ahUKEwjR3vewvLD6AhVQct4KHfBvCe4Q4dUDCA4&uact=5&oq=Husky&gs_lcp=Cgdnd3Mtd2l6EAMyCAguENQCEMsBMgUIABCABDIFCAAQywEyBQgAEMsBMgUIABDLATIFCAAQywEyBQgAEMsBMgUIABDLATIFCAAQywEyBQgAEMsBOgoIABBHENYEELADOg0IABBHENYEELADEMkDOgcIABCwAxBDOg0IABDkAhDWBBCwAxgBOhUILhDHARDRAxDUAhDIAxCwAxBDGAI6DAguEMgDELADEEMYAjoUCC4QxwEQ0QMQyAMQsAMQChBDGAJKBAhBGABKBAhGGAFQxQRYxQRggAhoA3ABeACAAaIBiAGiAZIBAzAuMZgBAKABAqABAcgBE8ABAdoBBggBEAEYCdoBBggCEAEYCA&sclient=gws-wiz" className={styles.card}>
            <h2>Husky &rarr;</h2>
            <p>Find Husky Dog on search engine</p>
          </a>

          <a
            href="https://www.google.com/search?q=KFC&oq=KFC+&aqs=chrome..69i57j35i39j0i512l2j46i175i199i512j0i512l2j46i175i199i512l2j46i199i465i512.1522j0j9&sourceid=chrome&ie=UTF-8"
            className={styles.card}
          >
            <h2>KFC Chicken &rarr;</h2>
            <p>Discover KFC Chicken on search engine.</p>
          </a>

          <a
            href="https://www.google.com/search?q=polar+bears&sxsrf=ALiCzsaQfRjZI-hHV8dxq2-VQOsjB3IUlQ%3A1664127278995&ei=LpEwY6a1PMKkwAPvxpL4Bw&ved=0ahUKEwimhM2avbD6AhVCEnAKHW-jBH8Q4dUDCA4&uact=5&oq=polar+bears&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEMsBMgUILhDLATIFCAAQywEyBQgAEMsBMgUIABDLATIFCAAQywEyBQgAEMsBMgUIABDLATIFCAAQywEyBQgAEMsBOgoIABBHENYEELADOgcIABCwAxBDOhIILhDHARDRAxDIAxCwAxBDGAE6DwguENQCEMgDELADEEMYAUoECEEYAEoECEYYAFDOBFjOBGDfC2gCcAF4AIABvgGIAb4BkgEDMC4xmAEAoAECoAEByAELwAEB2gEECAEYCA&sclient=gws-wiz"
            className={styles.card}
          >
            <h2>Polar Bears &rarr;</h2>
            <p>
              See Polar Bear on search engine.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          
        </a>
      </footer>
    </div>
  )
}
